import 'country_localizations.dart';

/// Indonesian localization for country names
class CountryLocalizationsId extends CountryLocalizations {
  CountryLocalizationsId() : super('id');

  @override
  String getCountryName(String countryCode) {
    return _countryNames[countryCode] ?? countryCode;
  }

  @override
  Map<String, String> get allCountryNames => _countryNames;

  @override
  String get selectCountry => 'Pilih Negara';

  @override
  String get searchCountry => 'Cari negara...';

  @override
  String get selectYourCountry => 'Pilih negara Anda';

  static const Map<String, String> _countryNames = {
    "RU": "Rusia",
    "US": "Amerika Serikat",
    "GB": "Britania Raya",
    "DE": "Jerman",
    "FR": "Prancis",
    "IT": "Italia",
    "ES": "Spanyol",
    "CA": "Kanada",
    "AU": "Australia",
    "JP": "Jepang",
    "CN": "Tiongkok",
    "IN": "India",
    "BR": "Brasil",
    "MX": "Meksiko",
    "AR": "Argentina",
    "CL": "Chili",
    "CO": "Kolombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "EC": "Ekuador",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "GY": "Guyana",
    "SR": "Suriname",
    "FK": "Kepulauan Falkland",
    "GF": "Guyana Prancis",
    "NL": "Belanda",
    "BE": "Belgia",
    "CH": "Swiss",
    "AT": "Austria",
    "SE": "Swedia",
    "NO": "Norwegia",
    "DK": "Denmark",
    "FI": "Finlandia",
    "PL": "Polandia",
    "CZ": "Republik Ceko",
    "SK": "Slovakia",
    "HU": "Hungaria",
    "RO": "Rumania",
    "BG": "Bulgaria",
    "HR": "Kroasia",
    "SI": "Slovenia",
    "EE": "Estonia",
    "LV": "Latvia",
    "LT": "Lituania",
    "UA": "Ukraina",
    "BY": "Belarus",
    "MD": "Moldova",
    "GE": "Georgia",
    "AM": "Armenia",
    "AZ": "Azerbaijan",
    "KZ": "Kazakhstan",
    "UZ": "Uzbekistan",
    "KG": "Kyrgyzstan",
    "TJ": "Tajikistan",
    "TM": "Turkmenistan",
    "TR": "Turki",
    "GR": "Yunani",
    "PT": "Portugal",
    "IE": "Irlandia",
    "IS": "Islandia",
    "MT": "Malta",
    "CY": "Siprus",
    "LU": "Luksemburg",
    "MC": "Monako",
    "LI": "Liechtenstein",
    "SM": "San Marino",
    "VA": "Vatikan",
    "AD": "Andorra",
    "AL": "Albania",
    "AX": "Kepulauan Åland",
    "BA": "Bosnia dan Herzegovina",
    "BN": "Brunei",
    "BT": "Bhutan",
    "FO": "Kepulauan Faroe",
    "GG": "Guernsey",
    "GI": "Gibraltar",
    "IM": "Pulau Man",
    "JE": "Jersey",
    "KY": "Kepulauan Cayman",
    "LK": "Sri Lanka",
    "ME": "Montenegro",
    "MK": "Makedonia Utara",
    "MN": "Mongolia",
    "MV": "Maladewa",
    "NP": "Nepal",
    "RS": "Serbia",
    "SJ": "Svalbard dan Jan Mayen",
    "TL": "Timor Leste",
    "UM": "Kepulauan Terluar Kecil Amerika Serikat",
    "XK": "Kosovo",
    "KR": "Korea Selatan",
    "KP": "Korea Utara",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "MO": "Makau",
    "SG": "Singapura",
    "MY": "Malaysia",
    "TH": "Thailand",
    "VN": "Vietnam",
    "PH": "Filipina",
    "ID": "Indonesia",
    "MM": "Myanmar",
    "LA": "Laos",
    "KH": "Kamboja",
    "BD": "Bangladesh",
    "PK": "Pakistan",
    "AF": "Afghanistan",
    "IR": "Iran",
    "IQ": "Irak",
    "SY": "Suriah",
    "LB": "Lebanon",
    "JO": "Yordania",
    "IL": "Israel",
    "PS": "Palestina",
    "SA": "Arab Saudi",
    "AE": "Uni Emirat Arab",
    "QA": "Qatar",
    "KW": "Kuwait",
    "BH": "Bahrain",
    "OM": "Oman",
    "YE": "Yaman",
    "EG": "Mesir",
    "LY": "Libya",
    "TN": "Tunisia",
    "DZ": "Aljazair",
    "MA": "Maroko",
    "SD": "Sudan",
    "SS": "Sudan Selatan",
    "ET": "Etiopia",
    "ER": "Eritrea",
    "DJ": "Djibouti",
    "SO": "Somalia",
    "KE": "Kenya",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "RW": "Rwanda",
    "BI": "Burundi",
    "MZ": "Mozambik",
    "ZW": "Zimbabwe",
    "ZM": "Zambia",
    "MW": "Malawi",
    "BW": "Botswana",
    "NA": "Namibia",
    "ZA": "Afrika Selatan",
    "LS": "Lesotho",
    "SZ": "Eswatini",
    "MG": "Madagaskar",
    "MU": "Mauritius",
    "SC": "Seychelles",
    "KM": "Komoro",
    "RE": "Réunion",
    "YT": "Mayotte",
    "NG": "Nigeria",
    "GH": "Ghana",
    "CI": "Pantai Gading",
    "BF": "Burkina Faso",
    "ML": "Mali",
    "NE": "Niger",
    "TD": "Chad",
    "CM": "Kamerun",
    "CF": "Republik Afrika Tengah",
    "CG": "Republik Kongo",
    "CD": "Republik Demokratik Kongo",
    "GA": "Gabon",
    "GQ": "Guinea Khatulistiwa",
    "ST": "São Tomé dan Príncipe",
    "AO": "Angola",
    "GW": "Guinea-Bissau",
    "GN": "Guinea",
    "SL": "Sierra Leone",
    "LR": "Liberia",
    "TG": "Togo",
    "BJ": "Benin",
    "SN": "Senegal",
    "GM": "Gambia",
    "CV": "Tanjung Verde",
    "MR": "Mauritania",
    "EH": "Sahara Barat",
    "NZ": "Selandia Baru",
    "FJ": "Fiji",
    "PG": "Papua Nugini",
    "SB": "Kepulauan Solomon",
    "VU": "Vanuatu",
    "NC": "Kaledonia Baru",
    "PF": "Polinesia Prancis",
    "TO": "Tonga",
    "WS": "Samoa",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "PW": "Palau",
    "MH": "Kepulauan Marshall",
    "FM": "Mikronesia",
    "CK": "Kepulauan Cook",
    "NU": "Niue",
    "TK": "Tokelau",
    "AS": "Samoa Amerika",
    "GU": "Guam",
    "MP": "Kepulauan Mariana Utara",
    "PR": "Puerto Riko",
    "VI": "Kepulauan Virgin Amerika Serikat",
    "GP": "Guadeloupe",
    "MQ": "Martinique",
    "BL": "Saint Barthélemy",
    "MF": "Saint Martin",
    "AW": "Aruba",
    "CW": "Curaçao",
    "SX": "Sint Maarten",
    "BQ": "Belanda Karibia",
    "TC": "Kepulauan Turks dan Caicos",
    "AI": "Anguilla",
    "VG": "Kepulauan Virgin Britania Raya",
    "MS": "Montserrat",
    "DM": "Dominika",
    "GD": "Grenada",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent dan Grenadines",
    "BB": "Barbados",
    "TT": "Trinidad dan Tobago",
    "JM": "Jamaika",
    "HT": "Haiti",
    "DO": "Republik Dominika",
    "CU": "Kuba",
    "BS": "Bahama",
    "KN": "Saint Kitts dan Nevis",
    "AG": "Antigua dan Barbuda",
    "NI": "Nikaragua",
    "CR": "Kosta Rika",
    "PA": "Panama",
    "HN": "Honduras",
    "SV": "El Salvador",
    "GT": "Guatemala",
    "BZ": "Belize",
    "GL": "Greenland",
    "PM": "Saint Pierre dan Miquelon",
    "BM": "Bermuda",
    "IO": "Wilayah Samudra Hindia Britania",
    "SH": "Saint Helena",
    "AC": "Pulau Ascension",
    "TA": "Tristan da Cunha",
    "CX": "Pulau Natal",
    "CC": "Kepulauan Cocos",
    "NF": "Pulau Norfolk",
    "AQ": "Antarktika",
    "BV": "Pulau Bouvet",
    "TF": "Wilayah Selatan Prancis",
    "HM": "Pulau Heard dan Kepulauan McDonald",
    "GS": "Georgia Selatan dan Kepulauan Sandwich Selatan",
    "PN": "Pitcairn",
    "WF": "Wallis dan Futuna"
  };
}
