import 'country_localizations.dart';

/// Polish localization for country names
class CountryLocalizationsPl extends CountryLocalizations {
  CountryLocalizationsPl() : super('pl');

  @override
  String getCountryName(String countryCode) {
    return _countryNames[countryCode] ?? countryCode;
  }

  @override
  Map<String, String> get allCountryNames => _countryNames;

  @override
  String get selectCountry => 'Wybierz kraj';

  @override
  String get searchCountry => 'Szukaj kraju...';

  @override
  String get selectYourCountry => 'Wybierz swój kraj';

  static const Map<String, String> _countryNames = {
    "RU": "Rosja",
    "US": "Stany Zjednoczone",
    "GB": "Wielka Brytania",
    "DE": "Niemcy",
    "FR": "Francja",
    "IT": "Włochy",
    "ES": "Hiszpania",
    "CA": "Kanada",
    "AU": "Australia",
    "JP": "Japonia",
    "CN": "Chiny",
    "IN": "Indie",
    "BR": "Brazylia",
    "MX": "Meksyk",
    "AR": "Argentyna",
    "CL": "Chile",
    "CO": "Kolumbia",
    "PE": "Peru",
    "VE": "Wenezuela",
    "EC": "Ekwador",
    "BO": "Boliwia",
    "PY": "Paragwaj",
    "UY": "Urugwaj",
    "GY": "Gujana",
    "SR": "Surinam",
    "FK": "Falklandy",
    "GF": "Gujana Francuska",
    "NL": "Holandia",
    "BE": "Belgia",
    "CH": "Szwajcaria",
    "AT": "Austria",
    "SE": "Szwecja",
    "NO": "Norwegia",
    "DK": "Dania",
    "FI": "Finlandia",
    "PL": "Polska",
    "CZ": "Czechy",
    "SK": "Słowacja",
    "HU": "Węgry",
    "RO": "Rumunia",
    "BG": "Bułgaria",
    "HR": "Chorwacja",
    "SI": "Słowenia",
    "EE": "Estonia",
    "LV": "Łotwa",
    "LT": "Litwa",
    "UA": "Ukraina",
    "BY": "Białoruś",
    "MD": "Mołdawia",
    "GE": "Gruzja",
    "AM": "Armenia",
    "AZ": "Azerbejdżan",
    "KZ": "Kazachstan",
    "UZ": "Uzbekistan",
    "KG": "Kirgistan",
    "TJ": "Tadżykistan",
    "TM": "Turkmenistan",
    "TR": "Turcja",
    "GR": "Grecja",
    "PT": "Portugalia",
    "IE": "Irlandia",
    "IS": "Islandia",
    "MT": "Malta",
    "CY": "Cypr",
    "LU": "Luksemburg",
    "MC": "Monako",
    "LI": "Liechtenstein",
    "SM": "San Marino",
    "VA": "Watykan",
    "AD": "Andora",
    "AL": "Albania",
    "AX": "Wyspy Alandzkie",
    "BA": "Bośnia i Hercegowina",
    "BN": "Brunei",
    "BT": "Bhutan",
    "FO": "Wyspy Owcze",
    "GG": "Guernsey",
    "GI": "Gibraltar",
    "IM": "Wyspa Man",
    "JE": "Jersey",
    "KY": "Kajmany",
    "LK": "Sri Lanka",
    "ME": "Czarnogóra",
    "MK": "Macedonia Północna",
    "MN": "Mongolia",
    "MV": "Malediwy",
    "NP": "Nepal",
    "RS": "Serbia",
    "SJ": "Svalbard i Jan Mayen",
    "TL": "Timor Wschodni",
    "UM": "Dalekie Wyspy Mniejsze Stanów Zjednoczonych",
    "XK": "Kosowo",
    "KR": "Korea Południowa",
    "KP": "Korea Północna",
    "TW": "Tajwan",
    "HK": "Hongkong",
    "MO": "Makau",
    "SG": "Singapur",
    "MY": "Malezja",
    "TH": "Tajlandia",
    "VN": "Wietnam",
    "PH": "Filipiny",
    "ID": "Indonezja",
    "MM": "Mjanma",
    "LA": "Laos",
    "KH": "Kambodża",
    "BD": "Bangladesz",
    "PK": "Pakistan",
    "AF": "Afganistan",
    "IR": "Iran",
    "IQ": "Irak",
    "SY": "Syria",
    "LB": "Liban",
    "JO": "Jordania",
    "IL": "Izrael",
    "PS": "Palestyna",
    "SA": "Arabia Saudyjska",
    "AE": "Zjednoczone Emiraty Arabskie",
    "QA": "Katar",
    "KW": "Kuwejt",
    "BH": "Bahrajn",
    "OM": "Oman",
    "YE": "Jemen",
    "EG": "Egipt",
    "LY": "Libia",
    "TN": "Tunezja",
    "DZ": "Algieria",
    "MA": "Maroko",
    "SD": "Sudan",
    "SS": "Sudan Południowy",
    "ET": "Etiopia",
    "ER": "Erytrea",
    "DJ": "Dżibuti",
    "SO": "Somalia",
    "KE": "Kenia",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "RW": "Rwanda",
    "BI": "Burundi",
    "MZ": "Mozambik",
    "ZW": "Zimbabwe",
    "ZM": "Zambia",
    "MW": "Malawi",
    "BW": "Botswana",
    "NA": "Namibia",
    "ZA": "Republika Południowej Afryki",
    "LS": "Lesotho",
    "SZ": "Eswatini",
    "MG": "Madagaskar",
    "MU": "Mauritius",
    "SC": "Seszele",
    "KM": "Komory",
    "RE": "Reunion",
    "YT": "Majotta",
    "NG": "Nigeria",
    "GH": "Ghana",
    "CI": "Wybrzeże Kości Słoniowej",
    "BF": "Burkina Faso",
    "ML": "Mali",
    "NE": "Niger",
    "TD": "Czad",
    "CM": "Kamerun",
    "CF": "Republika Środkowoafrykańska",
    "CG": "Republika Konga",
    "CD": "Demokratyczna Republika Konga",
    "GA": "Gabon",
    "GQ": "Gwinea Równikowa",
    "ST": "Wyspy Świętego Tomasza i Książęca",
    "AO": "Angola",
    "GW": "Gwinea Bissau",
    "GN": "Gwinea",
    "SL": "Sierra Leone",
    "LR": "Liberia",
    "TG": "Togo",
    "BJ": "Benin",
    "SN": "Senegal",
    "GM": "Gambia",
    "CV": "Wyspy Zielonego Przylądka",
    "MR": "Mauretania",
    "EH": "Sahara Zachodnia",
    "NZ": "Nowa Zelandia",
    "FJ": "Fidżi",
    "PG": "Papua Nowa Gwinea",
    "SB": "Wyspy Salomona",
    "VU": "Vanuatu",
    "NC": "Nowa Kaledonia",
    "PF": "Polinezja Francuska",
    "TO": "Tonga",
    "WS": "Samoa",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "PW": "Palau",
    "MH": "Wyspy Marshalla",
    "FM": "Mikronezja",
    "CK": "Wyspy Cooka",
    "NU": "Niue",
    "TK": "Tokelau",
    "AS": "Samoa Amerykańskie",
    "GU": "Guam",
    "MP": "Mariany Północne",
    "PR": "Portoryko",
    "VI": "Wyspy Dziewicze Stanów Zjednoczonych",
    "GP": "Gwadelupa",
    "MQ": "Martynika",
    "BL": "Saint Barthélemy",
    "MF": "Saint Martin",
    "AW": "Aruba",
    "CW": "Curaçao",
    "SX": "Sint Maarten",
    "BQ": "Holandia Karaibska",
    "TC": "Turks i Caicos",
    "AI": "Anguilla",
    "VG": "Brytyjskie Wyspy Dziewicze",
    "MS": "Montserrat",
    "DM": "Dominika",
    "GD": "Grenada",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent i Grenadyny",
    "BB": "Barbados",
    "TT": "Trynidad i Tobago",
    "JM": "Jamaika",
    "HT": "Haiti",
    "DO": "Republika Dominikańska",
    "CU": "Kuba",
    "BS": "Bahamy",
    "KN": "Saint Kitts i Nevis",
    "AG": "Antigua i Barbuda",
    "NI": "Nikaragua",
    "CR": "Kostaryka",
    "PA": "Panama",
    "HN": "Honduras",
    "SV": "Salwador",
    "GT": "Gwatemala",
    "BZ": "Belize",
    "GL": "Grenlandia",
    "PM": "Saint Pierre i Miquelon",
    "BM": "Bermudy",
    "IO": "Brytyjskie Terytorium Oceanu Indyjskiego",
    "SH": "Święta Helena",
    "AC": "Wyspa Wniebowstąpienia",
    "TA": "Tristan da Cunha",
    "CX": "Wyspa Bożego Narodzenia",
    "CC": "Wyspy Kokosowe",
    "NF": "Wyspa Norfolk",
    "AQ": "Antarktyda",
    "BV": "Wyspa Bouveta",
    "TF": "Francuskie Terytoria Południowe",
    "HM": "Wyspy Heard i McDonalda",
    "GS": "Georgia Południowa i Sandwich Południowy",
    "PN": "Pitcairn",
    "WF": "Wallis i Futuna"
  };
}
