import 'country_localizations.dart';

/// Vietnamese localization for country names
class CountryLocalizationsVi extends CountryLocalizations {
  CountryLocalizationsVi() : super('vi');

  @override
  String getCountryName(String countryCode) {
    return _countryNames[countryCode] ?? countryCode;
  }

  @override
  Map<String, String> get allCountryNames => _countryNames;

  @override
  String get selectCountry => 'Chọn quốc gia';

  @override
  String get searchCountry => 'Tìm kiếm quốc gia...';

  @override
  String get selectYourCountry => 'Chọn quốc gia của bạn';

  static const Map<String, String> _countryNames = {
    "RU": "Nga",
    "US": "Hoa Kỳ",
    "GB": "Vương quốc Anh",
    "DE": "Đức",
    "FR": "Pháp",
    "IT": "Ý",
    "ES": "Tây Ban Nha",
    "CA": "Canada",
    "AU": "Úc",
    "JP": "Nhật Bản",
    "CN": "Trung Quốc",
    "IN": "Ấn Độ",
    "BR": "Brazil",
    "MX": "Mexico",
    "AR": "Argentina",
    "CL": "Chile",
    "CO": "Colombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "EC": "Ecuador",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "GY": "Guyana",
    "SR": "Suriname",
    "FK": "Quần đảo Falkland",
    "GF": "Guyane thuộc Pháp",
    "NL": "Hà Lan",
    "BE": "Bỉ",
    "CH": "Thụy Sĩ",
    "AT": "Áo",
    "SE": "Thụy Điển",
    "NO": "Na Uy",
    "DK": "Đan Mạch",
    "FI": "Phần Lan",
    "PL": "Ba Lan",
    "CZ": "Cộng hòa Séc",
    "SK": "Slovakia",
    "HU": "Hungary",
    "RO": "Romania",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "SI": "Slovenia",
    "EE": "Estonia",
    "LV": "Latvia",
    "LT": "Lithuania",
    "UA": "Ukraine",
    "BY": "Belarus",
    "MD": "Moldova",
    "GE": "Georgia",
    "AM": "Armenia",
    "AZ": "Azerbaijan",
    "KZ": "Kazakhstan",
    "UZ": "Uzbekistan",
    "KG": "Kyrgyzstan",
    "TJ": "Tajikistan",
    "TM": "Turkmenistan",
    "TR": "Thổ Nhĩ Kỳ",
    "GR": "Hy Lạp",
    "PT": "Bồ Đào Nha",
    "IE": "Ireland",
    "IS": "Iceland",
    "MT": "Malta",
    "CY": "Síp",
    "LU": "Luxembourg",
    "MC": "Monaco",
    "LI": "Liechtenstein",
    "SM": "San Marino",
    "VA": "Vatican",
    "AD": "Andorra",
    "AL": "Albania",
    "AX": "Quần đảo Åland",
    "BA": "Bosnia và Herzegovina",
    "BN": "Brunei",
    "BT": "Bhutan",
    "FO": "Quần đảo Faroe",
    "GG": "Guernsey",
    "GI": "Gibraltar",
    "IM": "Đảo Man",
    "JE": "Jersey",
    "KY": "Quần đảo Cayman",
    "LK": "Sri Lanka",
    "ME": "Montenegro",
    "MK": "Bắc Macedonia",
    "MN": "Mông Cổ",
    "MV": "Maldives",
    "NP": "Nepal",
    "RS": "Serbia",
    "SJ": "Svalbard và Jan Mayen",
    "TL": "Đông Timor",
    "UM": "Các đảo nhỏ xa của Hoa Kỳ",
    "XK": "Kosovo",
    "KR": "Hàn Quốc",
    "KP": "Triều Tiên",
    "TW": "Đài Loan",
    "HK": "Hồng Kông",
    "MO": "Ma Cao",
    "SG": "Singapore",
    "MY": "Malaysia",
    "TH": "Thái Lan",
    "VN": "Việt Nam",
    "PH": "Philippines",
    "ID": "Indonesia",
    "MM": "Myanmar",
    "LA": "Lào",
    "KH": "Campuchia",
    "BD": "Bangladesh",
    "PK": "Pakistan",
    "AF": "Afghanistan",
    "IR": "Iran",
    "IQ": "Iraq",
    "SY": "Syria",
    "LB": "Lebanon",
    "JO": "Jordan",
    "IL": "Israel",
    "PS": "Palestine",
    "SA": "Ả Rập Saudi",
    "AE": "Các Tiểu vương quốc Ả Rập Thống nhất",
    "QA": "Qatar",
    "KW": "Kuwait",
    "BH": "Bahrain",
    "OM": "Oman",
    "YE": "Yemen",
    "EG": "Ai Cập",
    "LY": "Libya",
    "TN": "Tunisia",
    "DZ": "Algeria",
    "MA": "Morocco",
    "SD": "Sudan",
    "SS": "Nam Sudan",
    "ET": "Ethiopia",
    "ER": "Eritrea",
    "DJ": "Djibouti",
    "SO": "Somalia",
    "KE": "Kenya",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "RW": "Rwanda",
    "BI": "Burundi",
    "MZ": "Mozambique",
    "ZW": "Zimbabwe",
    "ZM": "Zambia",
    "MW": "Malawi",
    "BW": "Botswana",
    "NA": "Namibia",
    "ZA": "Nam Phi",
    "LS": "Lesotho",
    "SZ": "Eswatini",
    "MG": "Madagascar",
    "MU": "Mauritius",
    "SC": "Seychelles",
    "KM": "Comoros",
    "RE": "Réunion",
    "YT": "Mayotte",
    "NG": "Nigeria",
    "GH": "Ghana",
    "CI": "Bờ Biển Ngà",
    "BF": "Burkina Faso",
    "ML": "Mali",
    "NE": "Niger",
    "TD": "Chad",
    "CM": "Cameroon",
    "CF": "Cộng hòa Trung Phi",
    "CG": "Cộng hòa Congo",
    "CD": "Cộng hòa Dân chủ Congo",
    "GA": "Gabon",
    "GQ": "Guinea Xích Đạo",
    "ST": "São Tomé và Príncipe",
    "AO": "Angola",
    "GW": "Guinea-Bissau",
    "GN": "Guinea",
    "SL": "Sierra Leone",
    "LR": "Liberia",
    "TG": "Togo",
    "BJ": "Benin",
    "SN": "Senegal",
    "GM": "Gambia",
    "CV": "Cape Verde",
    "MR": "Mauritania",
    "EH": "Tây Sahara",
    "NZ": "New Zealand",
    "FJ": "Fiji",
    "PG": "Papua New Guinea",
    "SB": "Quần đảo Solomon",
    "VU": "Vanuatu",
    "NC": "New Caledonia",
    "PF": "Polynesia thuộc Pháp",
    "TO": "Tonga",
    "WS": "Samoa",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "PW": "Palau",
    "MH": "Quần đảo Marshall",
    "FM": "Micronesia",
    "CK": "Quần đảo Cook",
    "NU": "Niue",
    "TK": "Tokelau",
    "AS": "Samoa thuộc Mỹ",
    "GU": "Guam",
    "MP": "Quần đảo Bắc Mariana",
    "PR": "Puerto Rico",
    "VI": "Quần đảo Virgin thuộc Mỹ",
    "GP": "Guadeloupe",
    "MQ": "Martinique",
    "BL": "Saint Barthélemy",
    "MF": "Saint Martin",
    "AW": "Aruba",
    "CW": "Curaçao",
    "SX": "Sint Maarten",
    "BQ": "Caribbean Hà Lan",
    "TC": "Quần đảo Turks và Caicos",
    "AI": "Anguilla",
    "VG": "Quần đảo Virgin thuộc Anh",
    "MS": "Montserrat",
    "DM": "Dominica",
    "GD": "Grenada",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent và Grenadines",
    "BB": "Barbados",
    "TT": "Trinidad và Tobago",
    "JM": "Jamaica",
    "HT": "Haiti",
    "DO": "Cộng hòa Dominica",
    "CU": "Cuba",
    "BS": "Bahamas",
    "KN": "Saint Kitts và Nevis",
    "AG": "Antigua và Barbuda",
    "NI": "Nicaragua",
    "CR": "Costa Rica",
    "PA": "Panama",
    "HN": "Honduras",
    "SV": "El Salvador",
    "GT": "Guatemala",
    "BZ": "Belize",
    "GL": "Greenland",
    "PM": "Saint Pierre và Miquelon",
    "BM": "Bermuda",
    "IO": "Lãnh thổ Ấn Độ Dương thuộc Anh",
    "SH": "Saint Helena",
    "AC": "Đảo Ascension",
    "TA": "Tristan da Cunha",
    "CX": "Đảo Giáng sinh",
    "CC": "Quần đảo Cocos",
    "NF": "Đảo Norfolk",
    "AQ": "Nam Cực",
    "BV": "Đảo Bouvet",
    "TF": "Lãnh thổ phía Nam thuộc Pháp",
    "HM": "Đảo Heard và Quần đảo McDonald",
    "GS": "Nam Georgia và Quần đảo Nam Sandwich",
    "PN": "Pitcairn",
    "WF": "Wallis và Futuna"
  };
}
