import 'country_localizations.dart';

/// Italian localization for country names
class CountryLocalizationsIt extends CountryLocalizations {
  CountryLocalizationsIt() : super('it');

  @override
  String getCountryName(String countryCode) {
    return _countryNames[countryCode] ?? countryCode;
  }

  @override
  Map<String, String> get allCountryNames => _countryNames;

  @override
  String get selectCountry => 'Seleziona Paese';

  @override
  String get searchCountry => 'Cerca paese...';

  @override
  String get selectYourCountry => 'Seleziona il tuo paese';

  static const Map<String, String> _countryNames = {
    "RU": "Russia",
    "US": "Stati Uniti",
    "GB": "Regno Unito",
    "DE": "Germania",
    "FR": "Francia",
    "IT": "Italia",
    "ES": "Spagna",
    "CA": "Canada",
    "AU": "Australia",
    "JP": "Giappone",
    "CN": "Cina",
    "IN": "India",
    "BR": "Brasile",
    "MX": "Messico",
    "AR": "Argentina",
    "CL": "Cile",
    "CO": "Colombia",
    "PE": "Perù",
    "VE": "Venezuela",
    "EC": "Ecuador",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "GY": "Guyana",
    "SR": "Suriname",
    "FK": "Isole Falkland",
    "GF": "Guyana Francese",
    "NL": "Paesi Bassi",
    "BE": "Belgio",
    "CH": "Svizzera",
    "AT": "Austria",
    "SE": "Svezia",
    "NO": "Norvegia",
    "DK": "Danimarca",
    "FI": "Finlandia",
    "PL": "Polonia",
    "CZ": "Repubblica Ceca",
    "SK": "Slovacchia",
    "HU": "Ungheria",
    "RO": "Romania",
    "BG": "Bulgaria",
    "HR": "Croazia",
    "SI": "Slovenia",
    "EE": "Estonia",
    "LV": "Lettonia",
    "LT": "Lituania",
    "UA": "Ucraina",
    "BY": "Bielorussia",
    "MD": "Moldavia",
    "GE": "Georgia",
    "AM": "Armenia",
    "AZ": "Azerbaigian",
    "KZ": "Kazakistan",
    "UZ": "Uzbekistan",
    "KG": "Kirghizistan",
    "TJ": "Tagikistan",
    "TM": "Turkmenistan",
    "TR": "Turchia",
    "GR": "Grecia",
    "PT": "Portogallo",
    "IE": "Irlanda",
    "IS": "Islanda",
    "MT": "Malta",
    "CY": "Cipro",
    "LU": "Lussemburgo",
    "MC": "Monaco",
    "LI": "Liechtenstein",
    "SM": "San Marino",
    "VA": "Città del Vaticano",
    "AD": "Andorra",
    "AL": "Albania",
    "AX": "Isole Åland",
    "BA": "Bosnia ed Erzegovina",
    "BN": "Brunei",
    "BT": "Bhutan",
    "FO": "Isole Fær Øer",
    "GG": "Guernsey",
    "GI": "Gibilterra",
    "IM": "Isola di Man",
    "JE": "Jersey",
    "KY": "Isole Cayman",
    "LK": "Sri Lanka",
    "ME": "Montenegro",
    "MK": "Macedonia del Nord",
    "MN": "Mongolia",
    "MV": "Maldive",
    "NP": "Nepal",
    "RS": "Serbia",
    "SJ": "Svalbard e Jan Mayen",
    "TL": "Timor Est",
    "UM": "Isole minori degli Stati Uniti",
    "XK": "Kosovo",
    "KR": "Corea del Sud",
    "KP": "Corea del Nord",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "MO": "Macao",
    "SG": "Singapore",
    "MY": "Malaysia",
    "TH": "Thailandia",
    "VN": "Vietnam",
    "PH": "Filippine",
    "ID": "Indonesia",
    "MM": "Myanmar",
    "LA": "Laos",
    "KH": "Cambogia",
    "BD": "Bangladesh",
    "PK": "Pakistan",
    "AF": "Afghanistan",
    "IR": "Iran",
    "IQ": "Iraq",
    "SY": "Siria",
    "LB": "Libano",
    "JO": "Giordania",
    "IL": "Israele",
    "PS": "Palestina",
    "SA": "Arabia Saudita",
    "AE": "Emirati Arabi Uniti",
    "QA": "Qatar",
    "KW": "Kuwait",
    "BH": "Bahrain",
    "OM": "Oman",
    "YE": "Yemen",
    "EG": "Egitto",
    "LY": "Libia",
    "TN": "Tunisia",
    "DZ": "Algeria",
    "MA": "Marocco",
    "SD": "Sudan",
    "SS": "Sudan del Sud",
    "ET": "Etiopia",
    "ER": "Eritrea",
    "DJ": "Gibuti",
    "SO": "Somalia",
    "KE": "Kenya",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "RW": "Ruanda",
    "BI": "Burundi",
    "MZ": "Mozambico",
    "ZW": "Zimbabwe",
    "ZM": "Zambia",
    "MW": "Malawi",
    "BW": "Botswana",
    "NA": "Namibia",
    "ZA": "Sudafrica",
    "LS": "Lesotho",
    "SZ": "Eswatini",
    "MG": "Madagascar",
    "MU": "Mauritius",
    "SC": "Seychelles",
    "KM": "Comore",
    "RE": "Riunione",
    "YT": "Mayotte",
    "NG": "Nigeria",
    "GH": "Ghana",
    "CI": "Costa d'Avorio",
    "BF": "Burkina Faso",
    "ML": "Mali",
    "NE": "Niger",
    "TD": "Ciad",
    "CM": "Camerun",
    "CF": "Repubblica Centrafricana",
    "CG": "Repubblica del Congo",
    "CD": "Repubblica Democratica del Congo",
    "GA": "Gabon",
    "GQ": "Guinea Equatoriale",
    "ST": "São Tomé e Príncipe",
    "AO": "Angola",
    "GW": "Guinea-Bissau",
    "GN": "Guinea",
    "SL": "Sierra Leone",
    "LR": "Liberia",
    "TG": "Togo",
    "BJ": "Benin",
    "SN": "Senegal",
    "GM": "Gambia",
    "CV": "Capo Verde",
    "MR": "Mauritania",
    "EH": "Sahara Occidentale",
    "NZ": "Nuova Zelanda",
    "FJ": "Figi",
    "PG": "Papua Nuova Guinea",
    "SB": "Isole Salomone",
    "VU": "Vanuatu",
    "NC": "Nuova Caledonia",
    "PF": "Polinesia Francese",
    "TO": "Tonga",
    "WS": "Samoa",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "PW": "Palau",
    "MH": "Isole Marshall",
    "FM": "Micronesia",
    "CK": "Isole Cook",
    "NU": "Niue",
    "TK": "Tokelau",
    "AS": "Samoa Americane",
    "GU": "Guam",
    "MP": "Isole Marianne Settentrionali",
    "PR": "Porto Rico",
    "VI": "Isole Vergini Americane",
    "GP": "Guadalupa",
    "MQ": "Martinica",
    "BL": "Saint-Barthélemy",
    "MF": "Saint-Martin",
    "AW": "Aruba",
    "CW": "Curaçao",
    "SX": "Sint Maarten",
    "BQ": "Paesi Bassi Caraibici",
    "TC": "Isole Turks e Caicos",
    "AI": "Anguilla",
    "VG": "Isole Vergini Britanniche",
    "MS": "Montserrat",
    "DM": "Dominica",
    "GD": "Grenada",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent e Grenadine",
    "BB": "Barbados",
    "TT": "Trinidad e Tobago",
    "JM": "Giamaica",
    "HT": "Haiti",
    "DO": "Repubblica Dominicana",
    "CU": "Cuba",
    "BS": "Bahamas",
    "KN": "Saint Kitts e Nevis",
    "AG": "Antigua e Barbuda",
    "NI": "Nicaragua",
    "CR": "Costa Rica",
    "PA": "Panama",
    "HN": "Honduras",
    "SV": "El Salvador",
    "GT": "Guatemala",
    "BZ": "Belize",
    "GL": "Groenlandia",
    "PM": "Saint-Pierre e Miquelon",
    "BM": "Bermuda",
    "IO": "Territorio Britannico dell'Oceano Indiano",
    "SH": "Sant'Elena",
    "AC": "Isola di Ascensione",
    "TA": "Tristan da Cunha",
    "CX": "Isola di Natale",
    "CC": "Isole Cocos",
    "NF": "Isola Norfolk",
    "AQ": "Antartide",
    "BV": "Isola Bouvet",
    "TF": "Terre Australi Francesi",
    "HM": "Isole Heard e McDonald",
    "GS": "Georgia del Sud e Isole Sandwich Meridionali",
    "PN": "Pitcairn",
    "WF": "Wallis e Futuna"
  };
}
