import 'country_localizations.dart';

/// Dutch localization for country names
class CountryLocalizationsNl extends CountryLocalizations {
  CountryLocalizationsNl() : super('nl');

  @override
  String getCountryName(String countryCode) {
    return _countryNames[countryCode] ?? countryCode;
  }

  @override
  Map<String, String> get allCountryNames => _countryNames;

  @override
  String get selectCountry => 'Selecteer Land';

  @override
  String get searchCountry => 'Zoek land...';

  @override
  String get selectYourCountry => 'Selecteer uw land';

  static const Map<String, String> _countryNames = {
    "RU": "Rusland",
    "US": "Verenigde Staten",
    "GB": "Verenigd Koninkrijk",
    "DE": "Duitsland",
    "FR": "Frankrijk",
    "IT": "Italië",
    "ES": "Spanje",
    "CA": "Canada",
    "AU": "Australië",
    "JP": "Japan",
    "CN": "China",
    "IN": "India",
    "BR": "Brazilië",
    "MX": "Mexico",
    "AR": "Argentinië",
    "CL": "Chili",
    "CO": "Colombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "EC": "Ecuador",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "GY": "Guyana",
    "SR": "Suriname",
    "FK": "Falklandeilanden",
    "GF": "Frans-Guyana",
    "NL": "Nederland",
    "BE": "België",
    "CH": "Zwitserland",
    "AT": "Oostenrijk",
    "SE": "Zweden",
    "NO": "Noorwegen",
    "DK": "Denemarken",
    "FI": "Finland",
    "PL": "Polen",
    "CZ": "Tsjechië",
    "SK": "Slowakije",
    "HU": "Hongarije",
    "RO": "Roemenië",
    "BG": "Bulgarije",
    "HR": "Kroatië",
    "SI": "Slovenië",
    "EE": "Estland",
    "LV": "Letland",
    "LT": "Litouwen",
    "UA": "Oekraïne",
    "BY": "Wit-Rusland",
    "MD": "Moldavië",
    "GE": "Georgië",
    "AM": "Armenië",
    "AZ": "Azerbeidzjan",
    "KZ": "Kazachstan",
    "UZ": "Oezbekistan",
    "KG": "Kirgizië",
    "TJ": "Tadzjikistan",
    "TM": "Turkmenistan",
    "TR": "Turkije",
    "GR": "Griekenland",
    "PT": "Portugal",
    "IE": "Ierland",
    "IS": "IJsland",
    "MT": "Malta",
    "CY": "Cyprus",
    "LU": "Luxemburg",
    "MC": "Monaco",
    "LI": "Liechtenstein",
    "SM": "San Marino",
    "VA": "Vaticaanstad",
    "AD": "Andorra",
    "AL": "Albanië",
    "AX": "Ålandeilanden",
    "BA": "Bosnië en Herzegovina",
    "BN": "Brunei",
    "BT": "Bhutan",
    "FO": "Faeröer",
    "GG": "Guernsey",
    "GI": "Gibraltar",
    "IM": "Isle of Man",
    "JE": "Jersey",
    "KY": "Caymaneilanden",
    "LK": "Sri Lanka",
    "ME": "Montenegro",
    "MK": "Noord-Macedonië",
    "MN": "Mongolië",
    "MV": "Maldiven",
    "NP": "Nepal",
    "RS": "Servië",
    "SJ": "Spitsbergen en Jan Mayen",
    "TL": "Oost-Timor",
    "UM": "Kleine afgelegen eilanden van de Verenigde Staten",
    "XK": "Kosovo",
    "KR": "Zuid-Korea",
    "KP": "Noord-Korea",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "MO": "Macau",
    "SG": "Singapore",
    "MY": "Maleisië",
    "TH": "Thailand",
    "VN": "Vietnam",
    "PH": "Filipijnen",
    "ID": "Indonesië",
    "MM": "Myanmar",
    "LA": "Laos",
    "KH": "Cambodja",
    "BD": "Bangladesh",
    "PK": "Pakistan",
    "AF": "Afghanistan",
    "IR": "Iran",
    "IQ": "Irak",
    "SY": "Syrië",
    "LB": "Libanon",
    "JO": "Jordanië",
    "IL": "Israël",
    "PS": "Palestina",
    "SA": "Saudi-Arabië",
    "AE": "Verenigde Arabische Emiraten",
    "QA": "Qatar",
    "KW": "Koeweit",
    "BH": "Bahrein",
    "OM": "Oman",
    "YE": "Jemen",
    "EG": "Egypte",
    "LY": "Libië",
    "TN": "Tunesië",
    "DZ": "Algerije",
    "MA": "Marokko",
    "SD": "Soedan",
    "SS": "Zuid-Soedan",
    "ET": "Ethiopië",
    "ER": "Eritrea",
    "DJ": "Djibouti",
    "SO": "Somalië",
    "KE": "Kenia",
    "TZ": "Tanzania",
    "UG": "Oeganda",
    "RW": "Rwanda",
    "BI": "Burundi",
    "MZ": "Mozambique",
    "ZW": "Zimbabwe",
    "ZM": "Zambia",
    "MW": "Malawi",
    "BW": "Botswana",
    "NA": "Namibië",
    "ZA": "Zuid-Afrika",
    "LS": "Lesotho",
    "SZ": "Eswatini",
    "MG": "Madagaskar",
    "MU": "Mauritius",
    "SC": "Seychellen",
    "KM": "Comoren",
    "RE": "Réunion",
    "YT": "Mayotte",
    "NG": "Nigeria",
    "GH": "Ghana",
    "CI": "Ivoorkust",
    "BF": "Burkina Faso",
    "ML": "Mali",
    "NE": "Niger",
    "TD": "Tsjaad",
    "CM": "Kameroen",
    "CF": "Centraal-Afrikaanse Republiek",
    "CG": "Congo-Brazzaville",
    "CD": "Congo-Kinshasa",
    "GA": "Gabon",
    "GQ": "Equatoriaal-Guinea",
    "ST": "São Tomé en Principe",
    "AO": "Angola",
    "GW": "Guinee-Bissau",
    "GN": "Guinee",
    "SL": "Sierra Leone",
    "LR": "Liberia",
    "TG": "Togo",
    "BJ": "Benin",
    "SN": "Senegal",
    "GM": "Gambia",
    "CV": "Kaapverdië",
    "MR": "Mauritanië",
    "EH": "Westelijke Sahara",
    "NZ": "Nieuw-Zeeland",
    "FJ": "Fiji",
    "PG": "Papoea-Nieuw-Guinea",
    "SB": "Salomonseilanden",
    "VU": "Vanuatu",
    "NC": "Nieuw-Caledonië",
    "PF": "Frans-Polynesië",
    "TO": "Tonga",
    "WS": "Samoa",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "PW": "Palau",
    "MH": "Marshalleilanden",
    "FM": "Micronesië",
    "CK": "Cookeilanden",
    "NU": "Niue",
    "TK": "Tokelau",
    "AS": "Amerikaans-Samoa",
    "GU": "Guam",
    "MP": "Noordelijke Marianen",
    "PR": "Puerto Rico",
    "VI": "Amerikaanse Maagdeneilanden",
    "GP": "Guadeloupe",
    "MQ": "Martinique",
    "BL": "Saint-Barthélemy",
    "MF": "Saint-Martin",
    "AW": "Aruba",
    "CW": "Curaçao",
    "SX": "Sint Maarten",
    "BQ": "Caribisch Nederland",
    "TC": "Turks- en Caicoseilanden",
    "AI": "Anguilla",
    "VG": "Britse Maagdeneilanden",
    "MS": "Montserrat",
    "DM": "Dominica",
    "GD": "Grenada",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent en de Grenadines",
    "BB": "Barbados",
    "TT": "Trinidad en Tobago",
    "JM": "Jamaica",
    "HT": "Haïti",
    "DO": "Dominicaanse Republiek",
    "CU": "Cuba",
    "BS": "Bahama's",
    "KN": "Saint Kitts en Nevis",
    "AG": "Antigua en Barbuda",
    "NI": "Nicaragua",
    "CR": "Costa Rica",
    "PA": "Panama",
    "HN": "Honduras",
    "SV": "El Salvador",
    "GT": "Guatemala",
    "BZ": "Belize",
    "GL": "Groenland",
    "PM": "Saint-Pierre en Miquelon",
    "BM": "Bermuda",
    "IO": "Brits Indische Oceaanterritorium",
    "SH": "Sint-Helena",
    "AC": "Ascension",
    "TA": "Tristan da Cunha",
    "CX": "Christmaseiland",
    "CC": "Cocoseilanden",
    "NF": "Norfolkeiland",
    "AQ": "Antarctica",
    "BV": "Bouveteiland",
    "TF": "Franse Zuidelijke en Antarctische Gebieden",
    "HM": "Heard en McDonaldeilanden",
    "GS": "Zuid-Georgia en de Zuidelijke Sandwicheilanden",
    "PN": "Pitcairneilanden",
    "WF": "Wallis en Futuna"
  };
}
