import 'country_localizations.dart';

/// German localization for country names
class CountryLocalizationsDe extends CountryLocalizations {
  /// Creates a new German localization instance.
  CountryLocalizationsDe() : super('de');

  @override
  String getCountryName(String countryCode) {
    return _countryNames[countryCode] ?? countryCode;
  }

  @override
  Map<String, String> get allCountryNames => _countryNames;

  @override
  String get selectCountry => 'Land auswählen';

  @override
  String get searchCountry => 'Land suchen...';

  @override
  String get selectYourCountry => 'Wählen Sie Ihr Land';

  static const Map<String, String> _countryNames = {
    "RU": "Russland",
    "US": "Vereinigte Staaten",
    "GB": "Vereinigtes Königreich",
    "DE": "Deutschland",
    "FR": "Frankreich",
    "IT": "Italien",
    "ES": "Spanien",
    "CA": "Kanada",
    "AU": "Australien",
    "JP": "Japan",
    "CN": "China",
    "IN": "Indien",
    "BR": "Brasilien",
    "MX": "Mexiko",
    "AR": "Argentinien",
    "CL": "Chile",
    "CO": "Kolumbien",
    "PE": "Peru",
    "VE": "Venezuela",
    "EC": "Ecuador",
    "BO": "Bolivien",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "GY": "Guyana",
    "SR": "Suriname",
    "FK": "Falklandinseln",
    "GF": "Französisch-Guayana",
    "NL": "Niederlande",
    "BE": "Belgien",
    "CH": "Schweiz",
    "AT": "Österreich",
    "SE": "Schweden",
    "NO": "Norwegen",
    "DK": "Dänemark",
    "FI": "Finnland",
    "PL": "Polen",
    "CZ": "Tschechische Republik",
    "SK": "Slowakei",
    "HU": "Ungarn",
    "RO": "Rumänien",
    "BG": "Bulgarien",
    "HR": "Kroatien",
    "SI": "Slowenien",
    "EE": "Estland",
    "LV": "Lettland",
    "LT": "Litauen",
    "UA": "Ukraine",
    "BY": "Weißrussland",
    "MD": "Moldawien",
    "GE": "Georgien",
    "AM": "Armenien",
    "AZ": "Aserbaidschan",
    "KZ": "Kasachstan",
    "UZ": "Usbekistan",
    "KG": "Kirgisistan",
    "TJ": "Tadschikistan",
    "TM": "Turkmenistan",
    "TR": "Türkei",
    "GR": "Griechenland",
    "PT": "Portugal",
    "IE": "Irland",
    "IS": "Island",
    "MT": "Malta",
    "CY": "Zypern",
    "LU": "Luxemburg",
    "MC": "Monaco",
    "LI": "Liechtenstein",
    "SM": "San Marino",
    "VA": "Vatikanstadt",
    "AD": "Andorra",
    "AL": "Albanien",
    "AX": "Ålandinseln",
    "BA": "Bosnien und Herzegowina",
    "BN": "Brunei",
    "BT": "Bhutan",
    "FO": "Färöer",
    "GG": "Guernsey",
    "GI": "Gibraltar",
    "IM": "Isle of Man",
    "JE": "Jersey",
    "KY": "Kaimaninseln",
    "LK": "Sri Lanka",
    "ME": "Montenegro",
    "MK": "Nordmazedonien",
    "MN": "Mongolei",
    "MV": "Malediven",
    "NP": "Nepal",
    "RS": "Serbien",
    "SJ": "Svalbard und Jan Mayen",
    "TL": "Osttimor",
    "UM": "Kleinere Amerikanische Überseeinseln",
    "XK": "Kosovo",
    "KR": "Südkorea",
    "KP": "Nordkorea",
    "TW": "Taiwan",
    "HK": "Hongkong",
    "MO": "Macau",
    "SG": "Singapur",
    "MY": "Malaysia",
    "TH": "Thailand",
    "VN": "Vietnam",
    "PH": "Philippinen",
    "ID": "Indonesien",
    "MM": "Myanmar",
    "LA": "Laos",
    "KH": "Kambodscha",
    "BD": "Bangladesch",
    "PK": "Pakistan",
    "AF": "Afghanistan",
    "IR": "Iran",
    "IQ": "Irak",
    "SY": "Syrien",
    "LB": "Libanon",
    "JO": "Jordanien",
    "IL": "Israel",
    "PS": "Palästina",
    "SA": "Saudi-Arabien",
    "AE": "Vereinigte Arabische Emirate",
    "QA": "Katar",
    "KW": "Kuwait",
    "BH": "Bahrain",
    "OM": "Oman",
    "YE": "Jemen",
    "EG": "Ägypten",
    "LY": "Libyen",
    "TN": "Tunesien",
    "DZ": "Algerien",
    "MA": "Marokko",
    "SD": "Sudan",
    "SS": "Südsudan",
    "ET": "Äthiopien",
    "ER": "Eritrea",
    "DJ": "Dschibuti",
    "SO": "Somalia",
    "KE": "Kenia",
    "TZ": "Tansania",
    "UG": "Uganda",
    "RW": "Ruanda",
    "BI": "Burundi",
    "MZ": "Mosambik",
    "ZW": "Simbabwe",
    "ZM": "Sambia",
    "MW": "Malawi",
    "BW": "Botswana",
    "NA": "Namibia",
    "ZA": "Südafrika",
    "LS": "Lesotho",
    "SZ": "Eswatini",
    "MG": "Madagaskar",
    "MU": "Mauritius",
    "SC": "Seychellen",
    "KM": "Komoren",
    "RE": "Réunion",
    "YT": "Mayotte",
    "NG": "Nigeria",
    "GH": "Ghana",
    "CI": "Elfenbeinküste",
    "BF": "Burkina Faso",
    "ML": "Mali",
    "NE": "Niger",
    "TD": "Tschad",
    "CM": "Kamerun",
    "CF": "Zentralafrikanische Republik",
    "CG": "Republik Kongo",
    "CD": "Demokratische Republik Kongo",
    "GA": "Gabun",
    "GQ": "Äquatorialguinea",
    "ST": "São Tomé und Príncipe",
    "AO": "Angola",
    "GW": "Guinea-Bissau",
    "GN": "Guinea",
    "SL": "Sierra Leone",
    "LR": "Liberia",
    "TG": "Togo",
    "BJ": "Benin",
    "SN": "Senegal",
    "GM": "Gambia",
    "CV": "Kap Verde",
    "MR": "Mauretanien",
    "EH": "Westsahara",
    "NZ": "Neuseeland",
    "FJ": "Fidschi",
    "PG": "Papua-Neuguinea",
    "SB": "Salomonen",
    "VU": "Vanuatu",
    "NC": "Neukaledonien",
    "PF": "Französisch-Polynesien",
    "TO": "Tonga",
    "WS": "Samoa",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "PW": "Palau",
    "MH": "Marshallinseln",
    "FM": "Mikronesien",
    "CK": "Cookinseln",
    "NU": "Niue",
    "TK": "Tokelau",
    "AS": "Amerikanisch-Samoa",
    "GU": "Guam",
    "MP": "Nördliche Marianen",
    "PR": "Puerto Rico",
    "VI": "Amerikanische Jungferninseln",
    "GP": "Guadeloupe",
    "MQ": "Martinique",
    "BL": "Saint-Barthélemy",
    "MF": "Saint-Martin",
    "AW": "Aruba",
    "CW": "Curaçao",
    "SX": "Sint Maarten",
    "BQ": "Karibische Niederlande",
    "TC": "Turks- und Caicosinseln",
    "AI": "Anguilla",
    "VG": "Britische Jungferninseln",
    "MS": "Montserrat",
    "DM": "Dominica",
    "GD": "Grenada",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent und die Grenadinen",
    "BB": "Barbados",
    "TT": "Trinidad und Tobago",
    "JM": "Jamaika",
    "HT": "Haiti",
    "DO": "Dominikanische Republik",
    "CU": "Kuba",
    "BS": "Bahamas",
    "KN": "Saint Kitts und Nevis",
    "AG": "Antigua und Barbuda",
    "NI": "Nicaragua",
    "CR": "Costa Rica",
    "PA": "Panama",
    "HN": "Honduras",
    "SV": "El Salvador",
    "GT": "Guatemala",
    "BZ": "Belize",
    "GL": "Grönland",
    "PM": "Saint-Pierre und Miquelon",
    "BM": "Bermuda",
    "IO": "Britisches Territorium im Indischen Ozean",
    "SH": "Sankt Helena",
    "AC": "Ascension",
    "TA": "Tristan da Cunha",
    "CX": "Weihnachtsinsel",
    "CC": "Kokosinseln",
    "NF": "Norfolkinsel",
    "AQ": "Antarktis",
    "BV": "Bouvetinsel",
    "TF": "Französische Süd- und Antarktisgebiete",
    "HM": "Heard und McDonaldinseln",
    "GS": "Südgeorgien und die Südlichen Sandwichinseln",
    "PN": "Pitcairninseln",
    "WF": "Wallis und Futuna"
  };
}
