import 'country_localizations.dart';

/// Portuguese localization for country names
class CountryLocalizationsPt extends CountryLocalizations {
  CountryLocalizationsPt() : super('pt');

  @override
  String getCountryName(String countryCode) {
    return _countryNames[countryCode] ?? countryCode;
  }

  @override
  Map<String, String> get allCountryNames => _countryNames;

  @override
  String get selectCountry => 'Selecionar país';

  @override
  String get searchCountry => 'Pesquisar país...';

  @override
  String get selectYourCountry => 'Selecione seu país';

  static const Map<String, String> _countryNames = {
    "RU": "Rússia",
    "US": "Estados Unidos",
    "GB": "Reino Unido",
    "DE": "Alemanha",
    "FR": "França",
    "IT": "Itália",
    "ES": "Espanha",
    "CA": "Canadá",
    "AU": "Austrália",
    "JP": "Japão",
    "CN": "China",
    "IN": "Índia",
    "BR": "Brasil",
    "MX": "México",
    "AR": "Argentina",
    "CL": "Chile",
    "CO": "Colômbia",
    "PE": "Peru",
    "VE": "Venezuela",
    "EC": "Equador",
    "BO": "Bolívia",
    "PY": "Paraguai",
    "UY": "Uruguai",
    "GY": "Guiana",
    "SR": "Suriname",
    "FK": "Ilhas Malvinas",
    "GF": "Guiana Francesa",
    "NL": "Países Baixos",
    "BE": "Bélgica",
    "CH": "Suíça",
    "AT": "Áustria",
    "SE": "Suécia",
    "NO": "Noruega",
    "DK": "Dinamarca",
    "FI": "Finlândia",
    "PL": "Polônia",
    "CZ": "República Tcheca",
    "SK": "Eslováquia",
    "HU": "Hungria",
    "RO": "Romênia",
    "BG": "Bulgária",
    "HR": "Croácia",
    "SI": "Eslovênia",
    "EE": "Estônia",
    "LV": "Letônia",
    "LT": "Lituânia",
    "UA": "Ucrânia",
    "BY": "Bielorrússia",
    "MD": "Moldávia",
    "GE": "Geórgia",
    "AM": "Armênia",
    "AZ": "Azerbaijão",
    "KZ": "Cazaquistão",
    "UZ": "Uzbequistão",
    "KG": "Quirguistão",
    "TJ": "Tajiquistão",
    "TM": "Turcomenistão",
    "TR": "Turquia",
    "GR": "Grécia",
    "PT": "Portugal",
    "IE": "Irlanda",
    "IS": "Islândia",
    "MT": "Malta",
    "CY": "Chipre",
    "LU": "Luxemburgo",
    "MC": "Mônaco",
    "LI": "Liechtenstein",
    "SM": "San Marino",
    "VA": "Cidade do Vaticano",
    "AD": "Andorra",
    "AL": "Albânia",
    "AX": "Ilhas Åland",
    "BA": "Bósnia e Herzegovina",
    "BN": "Brunei",
    "BT": "Butão",
    "FO": "Ilhas Faroé",
    "GG": "Guernsey",
    "GI": "Gibraltar",
    "IM": "Ilha de Man",
    "JE": "Jersey",
    "KY": "Ilhas Cayman",
    "LK": "Sri Lanka",
    "ME": "Montenegro",
    "MK": "Macedônia do Norte",
    "MN": "Mongólia",
    "MV": "Maldivas",
    "NP": "Nepal",
    "RS": "Sérvia",
    "SJ": "Svalbard e Jan Mayen",
    "TL": "Timor-Leste",
    "UM": "Ilhas Menores dos Estados Unidos",
    "XK": "Kosovo",
    "KR": "Coreia do Sul",
    "KP": "Coreia do Norte",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "MO": "Macau",
    "SG": "Singapura",
    "MY": "Malásia",
    "TH": "Tailândia",
    "VN": "Vietnã",
    "PH": "Filipinas",
    "ID": "Indonésia",
    "MM": "Myanmar",
    "LA": "Laos",
    "KH": "Camboja",
    "BD": "Bangladesh",
    "PK": "Paquistão",
    "AF": "Afeganistão",
    "IR": "Irã",
    "IQ": "Iraque",
    "SY": "Síria",
    "LB": "Líbano",
    "JO": "Jordânia",
    "IL": "Israel",
    "PS": "Palestina",
    "SA": "Arábia Saudita",
    "AE": "Emirados Árabes Unidos",
    "QA": "Catar",
    "KW": "Kuwait",
    "BH": "Bahrein",
    "OM": "Omã",
    "YE": "Iêmen",
    "EG": "Egito",
    "LY": "Líbia",
    "TN": "Tunísia",
    "DZ": "Argélia",
    "MA": "Marrocos",
    "SD": "Sudão",
    "SS": "Sudão do Sul",
    "ET": "Etiópia",
    "ER": "Eritreia",
    "DJ": "Djibuti",
    "SO": "Somália",
    "KE": "Quênia",
    "TZ": "Tanzânia",
    "UG": "Uganda",
    "RW": "Ruanda",
    "BI": "Burundi",
    "MZ": "Moçambique",
    "ZW": "Zimbábue",
    "ZM": "Zâmbia",
    "MW": "Malawi",
    "BW": "Botswana",
    "NA": "Namíbia",
    "ZA": "África do Sul",
    "LS": "Lesoto",
    "SZ": "Eswatini",
    "MG": "Madagascar",
    "MU": "Maurício",
    "SC": "Seicheles",
    "KM": "Comores",
    "RE": "Reunião",
    "YT": "Mayotte",
    "NG": "Nigéria",
    "GH": "Gana",
    "CI": "Costa do Marfim",
    "BF": "Burkina Faso",
    "ML": "Mali",
    "NE": "Níger",
    "TD": "Chade",
    "CM": "Camarões",
    "CF": "República Centro-Africana",
    "CG": "República do Congo",
    "CD": "República Democrática do Congo",
    "GA": "Gabão",
    "GQ": "Guiné Equatorial",
    "ST": "São Tomé e Príncipe",
    "AO": "Angola",
    "GW": "Guiné-Bissau",
    "GN": "Guiné",
    "SL": "Serra Leoa",
    "LR": "Libéria",
    "TG": "Togo",
    "BJ": "Benim",
    "SN": "Senegal",
    "GM": "Gâmbia",
    "CV": "Cabo Verde",
    "MR": "Mauritânia",
    "EH": "Saara Ocidental",
    "NZ": "Nova Zelândia",
    "FJ": "Fiji",
    "PG": "Papua-Nova Guiné",
    "SB": "Ilhas Salomão",
    "VU": "Vanuatu",
    "NC": "Nova Caledônia",
    "PF": "Polinésia Francesa",
    "TO": "Tonga",
    "WS": "Samoa",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "PW": "Palau",
    "MH": "Ilhas Marshall",
    "FM": "Micronésia",
    "CK": "Ilhas Cook",
    "NU": "Niue",
    "TK": "Tokelau",
    "AS": "Samoa Americana",
    "GU": "Guam",
    "MP": "Ilhas Marianas do Norte",
    "PR": "Porto Rico",
    "VI": "Ilhas Virgens Americanas",
    "GP": "Guadalupe",
    "MQ": "Martinica",
    "BL": "São Bartolomeu",
    "MF": "São Martinho",
    "AW": "Aruba",
    "CW": "Curaçao",
    "SX": "São Martinho",
    "BQ": "Caribe Holandês",
    "TC": "Ilhas Turcas e Caicos",
    "AI": "Anguilla",
    "VG": "Ilhas Virgens Britânicas",
    "MS": "Montserrat",
    "DM": "Dominica",
    "GD": "Granada",
    "LC": "Santa Lúcia",
    "VC": "São Vicente e Granadinas",
    "BB": "Barbados",
    "TT": "Trinidad e Tobago",
    "JM": "Jamaica",
    "HT": "Haiti",
    "DO": "República Dominicana",
    "CU": "Cuba",
    "BS": "Bahamas",
    "KN": "São Cristóvão e Névis",
    "AG": "Antígua e Barbuda",
    "NI": "Nicarágua",
    "CR": "Costa Rica",
    "PA": "Panamá",
    "HN": "Honduras",
    "SV": "El Salvador",
    "GT": "Guatemala",
    "BZ": "Belize",
    "GL": "Groenlândia",
    "PM": "São Pedro e Miquelon",
    "BM": "Bermudas",
    "IO": "Território Britânico do Oceano Índico",
    "SH": "Santa Helena",
    "AC": "Ascensão",
    "TA": "Tristão da Cunha",
    "CX": "Ilha do Natal",
    "CC": "Ilhas Cocos",
    "NF": "Ilha Norfolk",
    "AQ": "Antártida",
    "BV": "Ilha Bouvet",
    "TF": "Terras Austrais Francesas",
    "HM": "Ilha Heard e Ilhas McDonald",
    "GS": "Geórgia do Sul e Ilhas Sandwich do Sul",
    "PN": "Ilhas Pitcairn",
    "WF": "Wallis e Futuna"
  };
}
